# Site settings
# destination: ../
title: virtualkc
subtitle: Yet Another KC85 Emulator
email: floooh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    portable KC85 emulator written in C++
baseurl: "/virtualkc" # the subpath of your site, e.g. /blog/
twitter_username: flohofwoe
github_username:  floooh

# Build settings
highlighter: pygments
markdown: kramdown 

